"""Central configuration for the professional detector."""

CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

# Detection / calibration
CALIBRATION_SECONDS = 3.0
SMOOTHING_WINDOW = 7
MIN_CALIBRATION_SAMPLES = 25

# Drowsiness thresholds
REPEATED_CLOSURE_WINDOW = 30.0
REPEATED_CLOSURE_COUNT = 3
REPEATED_CLOSURE_MIN_SECONDS = 0.70
HEAD_EYE_COMBO_SECONDS = 0.80
YAWN_EYE_COMBO_SECONDS = 0.80
EAR_THRESHOLD = 0.21
EAR_CLOSED_RATIO = 0.72
EAR_WARNING_RATIO = 0.84
BLINK_CLOSED_THRESHOLD = 0.55

CLOSED_SECONDS = 1.2
WARNING_SECONDS = 0.55

# Yawning
MAR_THRESHOLD = 0.62
JAW_OPEN_THRESHOLD = 0.38
YAWN_SECONDS = 1.0

# Head pose
HEAD_TILT_THRESHOLD = 0.28
HEAD_PITCH_THRESHOLD = 0.42
HEAD_POSE_SECONDS = 1.5

# Alarm
ALARM_BEEP_INTERVAL = 0.48
ALARM_FREQUENCY = 1150
ALARM_DURATION_MS = 220
ALARM_VOLUME = 0.78

WINDOW_TITLE = "Drowsiness Detector Pro"
LOG_FILE = "data/events.csv"
